version: "3"

services:

  iris:
    image: iris
    build: .
    container_name: iris
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    environment:
      - NAME=MyNode
      - IP=192.168.0.1
      - API=8080
      - SOCKET=8081
      - PASSWORD=MyApiPassword
